### ISSUE TITLE
Index stat total documents count mismatch?

### ISSUE THREAD

**Issue by Vijay4657** [meilisearch/meilisearch-dotnet#132] opened 2021-06-15 11:50 UTC
We have created an index in our meilisearch server and pushed bulk data from our database into the index. We are using the meilisearch version - 0.20.0 The current number of documents we have retried from the below code is 76,252.

`var stats = await client.Index(index).GetStats();`
`Console.WriteLine(stats.NumberOfDocuments);`

After that we pushed two batches of data each containing 96 & 4 documents each. So totally 100 documents pushed to the index. But when we checked the documents using the above code. Count has increased to 76,259. Remaining 93 counts are not retrieved from the stats of the index.

We have also checked the status of the update ID's of the above two batches(96 & 4) using the below code and it is marked as "Processed".

`var updateStatus = await client.Index(index).GetUpdateStatus(updateId);`
`Console.WriteLine(updateStatus.Status);`

Is there any delay in moving the processed updated Id documents into the "GetStats()" method "NumberOfDocuments" property as we are facing a discrepancy of 93 records.? Please provide any insight on this.

**Comment by curquiza** [comment] 2021-06-16 20:15
Hello @Vijay4657
Some users reported the stats route of the v0.20.0 was slow -> https://github.com/meilisearch/MeiliSearch/issues/1257
We did not succeed to reproduce, but we might have fixed it in the coming v0.21.0 with a new implementation of the stats route.
Also, if after a long time your route is still not up to date with the expected number of documents, it means you added (among the 100 documents) documents that was already in your MeiliSearch server. MeiliSearch looks at the `id` of your document, if a document with the same `id` exists, it will replace it, not add a new one.

If you did not push the same document twice (again, I mean using the same `id`), please, share with us your dataset and the exact steps you did so that we can reproduce the issue.

**Comment by curquiza** [comment] 2021-09-06 15:48
Closing this issue due to a lack of answer, feel free to re-open

**Closed as completed by curquiza** 2021-09-06 15:48 UTC
