### ISSUE TITLE
Error in driving operation meilishearch

### ISSUE THREAD

**Issue by 979170768** [meilisearch/meilisearch-dotnet#35] opened 2020-07-17 09:21 UTC
MeilisearchClient client = new MeilisearchClient("http://xxxxxx:7700", "masterKey"); 

   var index = await client.GetAllIndexes();  
   var ceshi =  await client.CreateIndex("movies1", "Id")

Error when getting all indexes:
System.MissingMethodException:“Method not found: 'System.IO.Stream System.Text.Encoding.CreateTranscodingStream(System.IO.Stream, System.Text.Encoding, System.Text.Encoding, Boolean)'.”

The data can be returned normally by using the post man test request interface:

 It may be a problem with the return value

**Comment by curquiza** [comment] 2020-07-21 08:31
Hello @979170768!

I did not succeed to reproduce your issue with:

```c#
using System.Threading.Tasks;

using Meilisearch;

namespace gettingStarted
{
    class Program
    {
        static async Task Main(string[] args)
        {
            MeilisearchClient client = new MeilisearchClient("http://localhost:7700", "masterKey");
            var index = await client.GetAllIndexes();
            var ceshi = await client.CreateIndex("movies1", "Id");
        }
    }
}
```

What is
- the version of the MeiliSearch package you use? The last one is currently `0.2.1`.
- the version of your MeiliSearch instance? The last one is currently the `0.12.0`.

**Comment by curquiza** [comment] 2020-09-28 15:27
I close this issue since we don't have enough information. Feel free to re-open it! 🙂

**Closed as completed by curquiza** 2020-09-28 15:27 UTC
