### ISSUE TITLE
C# add ShowMatchesPosition in SearchQuery setting made search output error

### ISSUE THREAD

**Issue by jennyesoo** [meilisearch/meilisearch-dotnet#428] opened 2023-05-31 04:34 UTC
**Describe the bug**
Using ShowMatchesPosition in a SearchQuery, the search output fails to match the structure.

**To Reproduce**

- SearchQuery setting

`
SearchQuery query = new SearchQuery
        {
            ShowMatchesPosition = true
        };
`

- output is

![image](https://github.com/meilisearch/meilisearch/assets/49374999/482f9039-09ff-452c-9dcc-0b29fe020818)

- I would like to search some query and then get error.  

code is 
`
ISearchable<IReadOnlyDictionary<string, string>> output = await _client.Index(_indexName).SearchAsync<IReadOnlyDictionary<string, string>>(input, query);
`

Error is 
`
System.Text.Json.JsonException: 'The JSON value could not be converted to System.String. Path: $.hits[0]._matchesPosition | LineNumber: 0 | BytePositionInLine: 36568.'
`

- check if There is an issue with the output structure in Meilisearch.ISearchable.cs 

![image](https://github.com/meilisearch/meilisearch/assets/49374999/2b7953c8-f53c-4c77-91a4-d068ee117392)

**Expected behavior**
The SearchAsync can be used flexibly.
`
ISearchable<T> output = await _client.Index(_indexName).SearchAsync<T>(input, query);
`

**Meilisearch version:**
Melisearch - [v1.2.0-rc.3]
C# -  <PackageReference Include="MeiliSearch" Version="0.14.2" />

**Comment by alallema** [comment] 2023-06-05 08:49
Hi @jennyesoo,
Thanks for raising this issue! It's the week of the engine release, so I'll take a look as soon as I can.

**Comment by jennyesoo** [comment] 2023-06-05 09:30
> Hi @jennyesoo, Thanks for raising this issue! It's the week of the engine release, so I'll take a look as soon as I can.

Thanks @alallema .

**Comment by ahmednfwela** [comment] 2023-06-27 01:52
This is not a bug actually, you are deserializing to `Dictionary<string, string>` and since `_matchesPosition` is not a string, it will throw.

I suggest deserializing to `JsonObject` instead

**Comment by alallema** [comment] 2023-06-27 18:27
Thank you so much @ahmednfwela, you're absolutely right 🚀. Sorry I didn't read more carefully.
On that note I will close this issue because this is not a bug.

**Closed as completed by alallema** 2023-06-27 18:27 UTC
Labels: bug

**Comment by jennyesoo** [comment] 2023-06-28 06:00
Hi, @ahmednfwela @alallema , thank you for your response.
I have now completed the conversion of the output to parse the JsonObject.
However, that is not the main point I want to emphasize.

When using `ShowMatchesPosition`, it generates two different output structures. My expectation is that `SearchAsync` should be flexible enough to handle these structures without requiring users to manually parse the JSON. Furthermore, `ISearchable` is unable to accurately interpret the structure.

I hope this conveys my intended message.

**Comment by ahmednfwela** [comment] 2023-06-28 11:53
@jennyesoo a similar situation is addressed here for _formatted
https://github.com/meilisearch/meilisearch-dotnet/pull/406
